FROM openjdk:11-slim
MAINTAINER phuocthanh.com
ADD target/accounts-0.0.1-SNAPSHOT.jar accounts-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["sh","-c","java -jar /accounts-0.0.1-SNAPSHOT.jar"]

#ENTRYPOINT ["java","-jar","/accounts-0.0.1-SNAPSHOT.jar"] 
