version: "3.9"

services:

 zipkin:
   image: openzipkin/zipkin
   mem_limit: 700m
   ports:
     - "9411:9411"
   networks:
     - charont-networks

 configserver:
   image: charont/configserver:latest
   mem_limit: 700m
   ports:
     - "8071:8071"
   networks:
     - charont-networks
   depends_on:
     - zipkin
   environment:
     SPRING_PROFILES_ACTIVE: default
     SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

 eurekaserver:
   image: charont/eurekaserver:latest
   mem_limit: 700m
   ports:
     - "8070:8070"
   networks:
     - charont-networks
   depends_on:
     - configserver
   deploy:
     restart_policy:
       condition: on-failure
       delay: 15s
       max_attempts: 3
       window: 120s
   environment:
     SPRING_PROFILES_ACTIVE: default
     SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
     SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

 accounts:
   image: charont/accounts:latest
   mem_limit: 700m
   ports:
     - "8081:8081"
   networks:
     - charont-networks
   depends_on:
     - configserver
     - eurekaserver
   deploy:
     restart_policy:
       condition: on-failure
       delay: 30s
       max_attempts: 3
       window: 120s
   environment:
     SPRING_PROFILES_ACTIVE: default
     SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
     SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

 loans:
   image: charont/loans:latest
   mem_limit: 700m
   ports:
     - "8090:8090"
   networks:
     - charont-networks
   depends_on:
     - configserver
     - eurekaserver
   deploy:
     restart_policy:
       condition: on-failure
       delay: 30s
       max_attempts: 3
       window: 120s
   environment:
     SPRING_PROFILES_ACTIVE: default
     SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
     SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

 cards:
   image: charont/cards:latest
   mem_limit: 700m
   ports:
     - "9000:9000"
   networks:
     - charont-networks
   depends_on:
     - configserver
     - eurekaserver
   deploy:
     restart_policy:
       condition: on-failure
       delay: 30s
       max_attempts: 3
       window: 120s
   environment:
     SPRING_PROFILES_ACTIVE: default
     SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
     SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
     
 gatewayserver:
   image: charont/gatewayserver:latest
   mem_limit: 700m
   ports:
     - "8072:8072"
   networks:
     - charont-networks
   depends_on:
     - configserver
     - eurekaserver
     - cards
     - loans
     - accounts
   deploy:
     restart_policy:
       condition: on-failure
       delay: 45s
       max_attempts: 3
       window: 180s
   environment:
     SPRING_PROFILES_ACTIVE: default
     SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
     SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

networks:
  charont-networks: