version: "3.9"

services:
 configserver:
   image: charont/configserver:latest
   mem_limit: 700m
   ports:
     - "8071:8071"
   networks:
     - charont-networks
 eurekaserver:
   image: charont/eurekaserver:latest
   mem_limit: 700m
   ports:
     - "8070:8070"
   networks:
     - charont-networks
   depends_on:
     - configserver
   deploy:
     restart_policy:
       condition: on-failure
       delay: 5s
       max_attempts: 3
       window: 120s
   environment:
     SPRING_PROFILES_ACTIVE: default
     SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
     
 accounts:
   image: charont/accounts:latest
   mem_limit: 700m
   ports:
    - "8080:8080"
   networks:
    - charont-networks
   depends_on:
     - configserver
     - eurekaserver
   deploy:
     restart_policy:
       condition: on-failure
       deplay: 5s
       max_attempts: 3
       window: 120s
   environment:
     SPRING_PROFILES_ACTIVE: dev
     SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eurekaserver:8070/eureka/
    
 loans:
   image: charont/loans:latest
   mem_limit: 700m
   ports:
    - "8090:8090"
   networks:
    - charont-networks
   depends_on:
     - configserver
     - eurekaserver
    deploy:
     restart_policy:
       condition: on-failure
       deplay: 5s
       max_attempts: 3
       window: 120s
   environment:
     SPRING_PROFILES_ACTIVE: dev
     SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eurekaserver:8070/eureka/
    
 cards:
   image: charont/cards:latest
   mem_limit: 700m
   ports:
    - "9000:9000"
   networks:
    - charont-networks
   depends_on:
     - configserver
     - eurekaserver
   deploy:
     restart_policy:
       condition: on-failure
       deplay: 5s
       max_attempts: 3
       window: 120s
   environment:
     SPRING_PROFILES_ACTIVE: dev
     SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eurekaserver:8070/eureka/

networks:
  charont-networks: